[package]
name = "gpu_scheduler_sim"
version = "0.1.0"
edition = "2024"

[dependencies]
csv = "1.3.1"
serde = { version = "1.0.219", features = ["derive"] }
rstest = "0.26.1"
public = "=0.2.2"
bitflags = "2.9.3"
rand = "0.9.2"
rstest_reuse = "0.7.0"